import { useMemo, useState } from 'react';
import { Stack, Title, Text, Code, Input, Badge } from '@eocrm/design-system';
import { Link as RouterLink } from 'react-router-dom';
import manifest from '@lib-source/components.manifest.json';
import styles from './ArchitecturePage.module.scss';

type Tier = 'primitive' | 'composition';

interface Entry {
  tier: Tier;
  cluster: string | null;
  composes: string[];
  composedBy: string[];
}

const TIER_LABEL: Record<Tier, string> = {
  primitive: 'Primitive',
  composition: 'Composition',
};

const CLUSTER_ORDER = ['Layout', 'Forms', 'Display', 'Feedback', 'Navigation', 'Overlays'];

/** Convert a component name to its `/components/<slug>` route. */
function componentRoute(name: string): string {
  // Apply the playground's existing kebab-case URL convention:
  // PascalCase → kebab-case, with a special case for "DatePickers" plural.
  const kebab = name
    .replace(/([A-Z])/g, '-$1')
    .toLowerCase()
    .replace(/^-/, '');
  return `/components/${kebab}`;
}

function ComponentLink({ name }: { name: string }) {
  return (
    <RouterLink to={componentRoute(name)} className={styles.componentLink}>
      <Code>{name}</Code>
    </RouterLink>
  );
}

function EntryCard({ name, entry }: { name: string; entry: Entry }) {
  return (
    <article id={`c-${name}`} className={styles.card}>
      <header className={styles.cardHeader}>
        <ComponentLink name={name} />
        {entry.cluster && <Badge tone="neutral">{entry.cluster}</Badge>}
        <Badge tone={entry.tier === 'primitive' ? 'info' : 'success'}>
          {TIER_LABEL[entry.tier]}
        </Badge>
      </header>

      {entry.composes.length > 0 && (
        <div className={styles.cardRow}>
          <span className={styles.rowLabel}>Composes</span>
          <span className={styles.rowChips}>
            {entry.composes.map((dep) => (
              <ComponentLink key={dep} name={dep} />
            ))}
          </span>
        </div>
      )}

      {entry.composedBy.length > 0 && (
        <div className={styles.cardRow}>
          <span className={styles.rowLabel}>Composed by</span>
          <span className={styles.rowChips}>
            {entry.composedBy.map((dep) => (
              <ComponentLink key={dep} name={dep} />
            ))}
          </span>
        </div>
      )}

      {entry.composes.length === 0 && entry.composedBy.length === 0 && (
        <Text size="sm" tone="muted">
          Standalone — no library-internal dependencies, not yet composed elsewhere.
        </Text>
      )}
    </article>
  );
}

interface Section {
  tier: Tier;
  title: string;
  description: string;
  entries: Array<[string, Entry]>;
}

/**
 * Read-only visualisation of the components.manifest.json dependency graph.
 * The manifest is generated by `packages/design-system/scripts/generate-manifest.mjs`
 * from the actual import statements in `src/components/`, so this page
 * always reflects the real graph — no per-component metadata to maintain.
 */
export function ArchitecturePage() {
  const [filter, setFilter] = useState('');

  const entries = useMemo(() => {
    const all = Object.entries(manifest as Record<string, Entry>);
    const needle = filter.trim().toLowerCase();
    if (!needle) return all;
    return all.filter(([name, entry]) => {
      if (name.toLowerCase().includes(needle)) return true;
      if (entry.cluster?.toLowerCase().includes(needle)) return true;
      if (entry.composes.some((d) => d.toLowerCase().includes(needle))) return true;
      if (entry.composedBy.some((d) => d.toLowerCase().includes(needle))) return true;
      return false;
    });
  }, [filter]);

  const primitives = entries.filter(([, e]) => e.tier === 'primitive');
  const compositions = entries.filter(([, e]) => e.tier === 'composition');

  const sections: Section[] = [
    {
      tier: 'primitive',
      title: 'Primitives',
      description:
        'Components with NO library-internal dependencies. They wrap a single HTML element (or compose only HTML + CSS) and form the foundation other components are built on.',
      entries: primitives,
    },
    {
      tier: 'composition',
      title: 'Compositions',
      description:
        'Components that import and reuse one or more primitives. When the right primitive exists, prefer the composition over hand-rolling — the dependency list shows you which primitives are already covered.',
      entries: compositions,
    },
  ];

  return (
    <Stack gap="lg" className={styles.page}>
      <header>
        <Stack gap="sm">
          <div className={styles.eyebrow}>Reference</div>
          <Title order={1}>Component architecture</Title>
          <Text tone="muted">
            Live dependency graph of every component in{' '}
            <Code>packages/design-system/src/components/</Code>. The classification —{' '}
            <Badge tone="info">Primitive</Badge> vs <Badge tone="success">Composition</Badge> —
            is derived from actual <Code>import</Code> statements, not hand-maintained
            metadata.
          </Text>
          <Text tone="muted" size="sm">
            <strong>{primitives.length}</strong> primitives ·{' '}
            <strong>{compositions.length}</strong> compositions · re-run{' '}
            <Code>npm run build:manifest -w @eocrm/design-system</Code> after adding a
            component.
          </Text>
        </Stack>
      </header>

      <Input
        type="search"
        placeholder="Filter by name, cluster, or dependency…"
        value={filter}
        onChange={(e) => setFilter(e.target.value)}
        aria-label="Filter components"
      />

      {entries.length === 0 && (
        <Text tone="muted">No components match {JSON.stringify(filter)}.</Text>
      )}

      {sections.map((section) => {
        if (section.entries.length === 0) return null;
        const grouped = groupByCluster(section.entries);
        return (
          <section key={section.tier} className={styles.tierSection}>
            <Stack gap="sm">
              <Title order={2}>
                {section.title}{' '}
                <Text as="span" tone="muted" size="sm">
                  ({section.entries.length})
                </Text>
              </Title>
              <Text tone="muted">{section.description}</Text>
            </Stack>

            {CLUSTER_ORDER.filter((cluster) => grouped[cluster]?.length).map((cluster) => (
              <div key={cluster} className={styles.clusterGroup}>
                <Title order={3} className={styles.clusterHeading}>
                  {cluster}{' '}
                  <Text as="span" tone="muted" size="sm">
                    ({grouped[cluster].length})
                  </Text>
                </Title>
                <div className={styles.cardGrid}>
                  {grouped[cluster].map(([name, entry]) => (
                    <EntryCard key={name} name={name} entry={entry} />
                  ))}
                </div>
              </div>
            ))}
          </section>
        );
      })}
    </Stack>
  );
}

function groupByCluster(entries: Array<[string, Entry]>): Record<string, Array<[string, Entry]>> {
  const out: Record<string, Array<[string, Entry]>> = {};
  for (const pair of entries) {
    const cluster = pair[1].cluster ?? 'Unclassified';
    (out[cluster] ??= []).push(pair);
  }
  return out;
}
